//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class GameWindow extends JPanel {
    private JButton chip5;
    private JButton chip100;
    private JButton chip10;
    private JButton chip250;
    private JButton chip25;
    private JButton chip500;
    private JButton chip50;
    private JButton chip1000;
    private JButton hitBtn;
    private JButton standBtn;
    private JButton doubleBtn;
    private JButton settingsBtn;
    private JButton musicBtn;
    private JButton statsBtn;
    private JLabel croupierHand;
    private JLabel playersHand;
    private JLabel balance;
    private JLabel currentBet;

    public GameWindow() {
        //construct components
        chip5 = new JButton ("");
        chip10 = new JButton ("");
        chip25 = new JButton ("");
        chip50 = new JButton ("");
        chip100 = new JButton ("");
        chip250 = new JButton ("");
        chip500 = new JButton ("");
        chip1000 = new JButton ("");

        hitBtn = new JButton ("HIT");
        standBtn = new JButton ("STAND");
        doubleBtn = new JButton ("DOUBLE");

        settingsBtn = new JButton ("Settings");
        musicBtn = new JButton ("Music");
        statsBtn = new JButton ("Stats");

        croupierHand = new JLabel ("croupier hand");
        playersHand = new JLabel ("players hand");

        balance = new JLabel ("Dostępne żetony");
        currentBet = new JLabel ("Aktualny zakład");

        chip5.setIcon(new ImageIcon(new ImageIcon("img/chip5.png").getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
        chip10.setIcon(new ImageIcon(new ImageIcon("img/chip10.png").getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
        chip25.setIcon(new ImageIcon(new ImageIcon("img/chip25.png").getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
        chip50.setIcon(new ImageIcon(new ImageIcon("img/chip50.png").getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
        chip100.setIcon(new ImageIcon(new ImageIcon("img/chip100.png").getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
        chip250.setIcon(new ImageIcon(new ImageIcon("img/chip250.png").getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
        chip500.setIcon(new ImageIcon(new ImageIcon("img/chip500.png").getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
        chip1000.setIcon(new ImageIcon(new ImageIcon("img/chip1000.png").getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));

        chip5.setBackground(Color.WHITE);
        chip10.setBackground(Color.WHITE);
        chip25.setBackground(Color.WHITE);
        chip50.setBackground(Color.WHITE);
        chip100.setBackground(Color.WHITE);
        chip250.setBackground(Color.WHITE);
        chip500.setBackground(Color.WHITE);
        chip1000.setBackground(Color.WHITE);

        hitBtn.setFont(new Font("Arial", Font.BOLD, 30));
        hitBtn.setForeground(Color.BLACK);
        hitBtn.setBackground(Color.GREEN);
        hitBtn.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        hitBtn.setFocusPainted(false);

        standBtn.setFont(new Font("Arial", Font.BOLD, 30));
        standBtn.setForeground(Color.BLACK);
        standBtn.setBackground(Color.RED);
        standBtn.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        standBtn.setFocusPainted(false);

        doubleBtn.setFont(new Font("Arial", Font.BOLD, 30));
        doubleBtn.setForeground(Color.BLACK);
        doubleBtn.setBackground(Color.cyan);
        doubleBtn.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
        doubleBtn.setFocusPainted(false);

        //adjust size and set layout
        setPreferredSize (new Dimension (1344, 756));
        setLayout (null);

        //add components
        add (chip5);
        add (chip100);
        add (chip10);
        add (chip250);
        add (chip25);
        add (chip500);
        add (chip50);
        add (chip1000);
        add (hitBtn);
        add (standBtn);
        add (doubleBtn);
        add (settingsBtn);
        add (musicBtn);
        add (statsBtn);
        add (croupierHand);
        add (playersHand);
        add (balance);
        add (currentBet);

        //set component bounds (only needed by Absolute Positioning)
        chip5.setBounds (0, 504, 168, 126);
        chip100.setBounds (0, 630, 168, 126);
        chip10.setBounds (168, 504, 168, 126);
        chip250.setBounds (168, 630, 168, 126);
        chip25.setBounds (336, 504, 168, 126);
        chip500.setBounds (336, 630, 168, 126);
        chip50.setBounds (504, 504, 168, 126);
        chip1000.setBounds (504, 630, 168, 126);
        hitBtn.setBounds (672, 504, 252, 252);
        standBtn.setBounds (924, 504, 252, 252);
        doubleBtn.setBounds (1176, 504, 168, 252);
        settingsBtn.setBounds (1090, 0, 84, 126);
        musicBtn.setBounds (1174, 0, 84, 126);
        statsBtn.setBounds (1258, 0, 84, 126);
        croupierHand.setBounds (1090, 378, 126, 126);
        playersHand.setBounds (1216, 378, 126, 126);
        balance.setBounds (1090, 126, 252, 126);
        currentBet.setBounds (1090, 252, 252, 126);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new GameWindow());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible (true);
    }
}